### ISSUE TITLE
mysql_db module complains about lack of no_log use

### ISSUE THREAD

**Issue by Berbe** [ansible-collections/ansible.mysql#33]
##### SUMMARY
A warning is being issued while no sensitive data is being displayed: defect in the module?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`mysql_db` module

##### ANSIBLE VERSION
```
ansible 2.10.1
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/venv/ansible/lib/python3.7/site-packages/ansible
  executable location = /home/user/venv/ansible/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### OS / ENVIRONMENT

```
Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE
```yaml
- name: Whatever
  mysql_db:
    name: test
    state: absent
    login_unix_socket: /what/ever
```

##### EXPECTED RESULTS
No warning

##### ACTUAL RESULTS
```
[WARNING]: Module did not set no_log for unsafe_login_password
```

**Comment by Andersson007** [comment]
@Berbe thanks for reporting the issue! I'm working on fixing this

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.mysql/pull/34
this is a false warning related to a new parameter, fixed

**Comment by Andersson007** [comment]
i've just merged the pr. Warnings should disappear in community.mysql 1.0.1 release, which is planned this week

**Comment by Andersson007** [comment]
@Berbe thanks for reporting this!

**Comment by madalinignisca** [comment]
Hi. I am on 11.1 and this warning still shows up.

STEPS TO REPRODUCE
```
  - name: add mysql db
    community.mysql.mysql_db:
      name: wp
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
```

**Comment by Andersson007** [comment]
@madalinignisca hi, looks like my fix was accidentally reverted by https://github.com/ansible-collections/community.mysql/pull/38.
Thanks for reporting this! I'll create a PR

**Comment by Andersson007** [comment]
Done, I'll merge https://github.com/ansible-collections/community.mysql/pull/74 after CI passed and will release the collection after https://github.com/ansible-collections/community.mysql/pull/71 merged (needs review).

**Comment by Andersson007** [comment]
I've just released community.mysql 1.1.2 containing the fix which tarbal is available [here](https://galaxy.ansible.com/community/mysql) to download and use. The changes will also appear in the next Ansible package patch release. How to install in manually, refer to [this document](https://docs.ansible.com/ansible/devel/user_guide/collections_using.html).

Thanks everyone!
